name: CI-compile

on:
  push:
  pull_request:

jobs:
  build-win:
    name: PMAP windows compilation
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup msbuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Build
        run: msbuild /p:PlatformToolset=v142 /p:Configuration=Release

      - uses: actions/upload-artifact@v3
        with:
          name: PMAP-wincli
          path: Release/PMAP.exe

      - uses: actions/upload-artifact@v3
        with:
          name: PMAP-wingui
          path: Release/PMAP-win.exe

      - name: Create release
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          title: "Latest development build"
          files: Release/PMAP.exe

      - name: Create release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: "${{ contains(github.ref, '-rc') }}"
          title: PMAP-${{ github.ref }}
          files: Release/PMAP.exe

  build-macos:
    name: PMAP macos compilation
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build
        run: |
          cd PMAP-unix
          make
          tar -zcvf PMAP-macos.tar.gz pmap

      - name: Build id
        run: |
          cd PMAP-unix
          make clean
          make ID_MANAGEMENT=1
          tar -zcvf PMAP-macos-id.tar.gz pmap

      - uses: actions/upload-artifact@v3
        with:
          name: PMAP-macos
          path: PMAP-unix/PMAP-macos.tar.gz

      - uses: actions/upload-artifact@v3
        with:
          name: PMAP-macos-id
          path: PMAP-unix/PMAP-macos-id.tar.gz

  build-linux:
    name: PMAP linux compilation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build
        run: |
          cd PMAP-unix
          make
          tar -zcvf PMAP-linux.tar.gz pmap

      - name: Build id
        run: |
          cd PMAP-unix
          make clean
          make ID_MANAGEMENT=1
          tar -zcvf PMAP-linux-id.tar.gz pmap

      - uses: actions/upload-artifact@v3
        with:
          name: PMAP-linux
          path: PMAP-unix/PMAP-linux.tar.gz

      - uses: actions/upload-artifact@v3
        with:
          name: PMAP-linux-id
          path: PMAP-unix/PMAP-linux-id.tar.gz
