name: CI-compile

on:
  push:
  pull_request:

jobs:
  build-win:
    name: PMAP windows compilation
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup msbuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Build
        run: msbuild /p:PlatformToolset=v142 /p:Configuration=Release

      - uses: actions/upload-artifact@v3
        with:
          name: PMAP.exe
          path: Release/PMAP.exe

      - uses: actions/upload-artifact@v3
        with:
          name: PMAP-win.exe
          path: Release/PMAP-win.exe

      - name: Create release
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          title: "Latest development build"
          files: Release/PMAP.exe

      - name: Create release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: "${{ contains(github.ref, '-rc') }}"
          title: PMAP-${{ github.ref }}
          files: Release/PMAP.exe

  build-macos:
    name: PMAP macos compilation
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build
        run: |
          cd PMAP-macos
          make
          tar -zcvf PMAP-macos.tar.gz pmap

      - uses: actions/upload-artifact@v3
        with:
          name: PMAP-macos
          path: PMAP-macos/PMAP-macos.tar.gz

  # build-linux:
  #   name: PMAP linux compilation
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout Repository
  #       uses: actions/checkout@v3

  #     - name: Build
  #       run: |
  #         cd PMAP-linux
  #         make
  #         tar -zcvf pmap.tar.gz pmap

  #     - uses: actions/upload-artifact@v3
  #       with:
  #         name: PMAP
  #         path: linux/pmap.tar.gz
